---

- name: Install vim
  apt:
    name: vim
    package: latest
    state: installed

- name: Install vim plugin manager
  shell:
    command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Create link to vim config file
  file:
    src: {{ anisble_dotfiles_home }}/vim/vimrc
    dest: $HOME/.vimrc
    state: present
    mode: link

- name: Install vim plugins
  shell:
    command: "vim -c PlugInstall" # Totally guessing here
